"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { Baby, ChevronDown, CirclePlus, ExternalLink, MapPin, Menu, MessageCircle, Navigation, ScanFace, Smile, Star, Stethoscope, X, type LucideIcon } from "lucide-react";
import { useState } from "react";

const whatsapp = "https://wa.me/5521993770229?text=Ol%C3%A1%2C%20LB%20Odontologia!%20Gostaria%20de%20agendar%20uma%20avalia%C3%A7%C3%A3o.";
const instagram = "https://www.instagram.com/lb.odontologia_/";
const address = "Edifício Center Offices - R. da Conceição, 125 - Sala 608 - Centro, Niterói - RJ, 24020-080";
const directions = "https://www.google.com/maps/dir/?api=1&destination=Edif%C3%ADcio%20Center%20Offices%2C%20Rua%20da%20Concei%C3%A7%C3%A3o%2C%20125%2C%20Sala%20608%2C%20Niter%C3%B3i%2C%20RJ";
const map = "https://www.google.com/maps?q=Edif%C3%ADcio%20Center%20Offices%2C%20Rua%20da%20Concei%C3%A7%C3%A3o%2C%20125%2C%20Sala%20608%2C%20Niter%C3%B3i%2C%20RJ&z=17&output=embed";
const googleReviews = "https://www.google.com/search?q=LB+Odontologia+Niter%C3%B3i+avalia%C3%A7%C3%B5es";

const team = [
  { name: "Dra. Larissa", specialty: "Equipe LB Odontologia", photo: "/team-larissa.png" },
  { name: "Dra. Beatriz", specialty: "Equipe LB Odontologia", photo: "/team-beatriz.png" },
  { name: "Dr. Fábio", specialty: "Equipe LB Odontologia", photo: "/team-fabio.png" },
  { name: "Dr. Vinícius", specialty: "Equipe LB Odontologia", photo: "/team-vinicius.png" },
  { name: "Dra. Larissa Santana", specialty: "Equipe LB Odontologia", photo: "/team-larissa-santana.png" },
  { name: "Dr. Paulo", specialty: "Equipe LB Odontologia", photo: "/team-paulo.png" },
];
const treatments: [string, string, string, LucideIcon][] = [
  ["01", "Ortodontia e Invisalign", "Alinhamento discreto e planejado para a sua rotina.", ScanFace],
  ["02", "Odontopediatria", "Cuidado acolhedor para os sorrisos que estão começando.", Baby],
  ["03", "Dentística e estética", "Naturalidade e harmonia em cada detalhe do sorriso.", Smile],
  ["04", "Endodontia e implantes", "Tecnologia e precisão para saúde e função oral.", CirclePlus],
  ["05", "Clínica geral", "Prevenção e acompanhamento para toda a família.", Stethoscope],
];
const testimonials = [
  { name: "Paciente da LB Odontologia", text: "Conheci a Dra. Larissa em 2019, fui indicada por um amigo. Desde o início os atendimentos sempre foram com muita clareza, eficiência e comprometimento, esclarecendo dúvidas. Muito simpática e educada. Mesmo na pandemia, fomos atendidos da mesma forma. Uma excelente profissional, trabalha com responsabilidade e dedicação aos seus pacientes. Parabéns." },
  { name: "Paciente da LB Odontologia", text: "Meu depoimento sobre a clínica não poderia ser outro, só posso elogiar o consultório pela dedicação, profissionais e competência para administração das consultas. A Doutora Larissa é diferenciada! Uma excelente profissional! E sempre com sorriso no rosto, alto astral." },
  { name: "Paciente da LB Odontologia", text: "Equipe maravilhosa! Amo a Dra. Larissa, um amor de pessoa, super atenciosa, carinhosa e talentosa. Serviços excelentes e a localização ótima no centro de Niterói. Trabalhos surpreendentes, sempre se preocupando com o paciente. Recomendo e muito!" },
];

const procedureCases = [
  { image: "/procedimentos-lb.png", alt: "Resultados de procedimentos odontológicos e estéticos realizados pela LB Odontologia em Niterói" },
];
const faqs = [
  { question: "O tratamento com implante dói?", answer: "O procedimento é planejado para oferecer conforto. A equipe orienta cada etapa, incluindo anestesia, cuidados e medicação quando indicada." },
  { question: "Quanto tempo leva a recuperação?", answer: "O tempo varia conforme o tratamento e as características de cada pessoa. Após a avaliação, a equipe apresenta um plano e orientações claras para sua recuperação." },
  { question: "A clínica atende convênio ou particular?", answer: "Entre em contato pelo WhatsApp para confirmar as opções de atendimento, valores e possibilidades para o seu tratamento." },
  { question: "Quantas consultas serão necessárias?", answer: "Cada sorriso tem necessidades próprias. Depois da avaliação, você recebe uma proposta de cuidado com as etapas necessárias para o seu caso." },
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, delay }}>{children}</motion.div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  return <main className="overflow-x-hidden bg-[#fbf8f1] text-[#283237]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-[#9a6a32]/15 bg-[#fcfaf5]/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 md:px-8"><a href="#inicio" className="flex items-center gap-3" aria-label="LB Odontologia"><span className="relative h-11 w-11 overflow-hidden rounded-full border border-[#c6a06a]/50 bg-[#faf5ea]"><Image src="/logo-lb.png" alt="Monograma LB da clínica LB Odontologia em Niterói" fill className="object-contain p-1" sizes="44px" /></span><span className="leading-tight"><b className="block text-[15px]">LB Odontologia</b><span className="text-xs text-[#6b6256]">Especializada</span></span></a><nav className="hidden items-center gap-7 text-sm font-medium text-[#43545d] lg:flex"><a href="#inicio">Início</a><a href="#equipe">Equipe</a><a href="#tratamentos">Tratamentos</a><a href="#localizacao">Localização</a></nav><div className="flex items-center gap-2"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-[#c99a55] to-[#9a6a32] px-3 py-2 text-xs font-bold text-white shadow-sm transition hover:brightness-105 sm:px-4 sm:text-sm"><MessageCircle size={17} /><span className="hidden sm:inline">Agendar avaliação</span></a><button className="grid h-10 w-10 place-items-center rounded-full bg-[#e8d8b9] text-[#244e63] lg:hidden" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div>{menuOpen && <nav className="border-t border-[#9a6a32]/15 bg-[#fcfaf5] px-5 py-5 lg:hidden"><a className="block py-3" href="#inicio" onClick={() => setMenuOpen(false)}>Início</a><a className="block py-3" href="#equipe" onClick={() => setMenuOpen(false)}>Equipe</a><a className="block py-3" href="#tratamentos" onClick={() => setMenuOpen(false)}>Tratamentos</a><a className="block py-3" href="#localizacao" onClick={() => setMenuOpen(false)}>Localização</a></nav>}</header>

    <section id="inicio" className="relative isolate min-h-[770px] overflow-hidden bg-[#fbf8f1] pt-[76px]"><div className="absolute left-1/2 top-24 -z-10 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-[#c99a55]/25 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center px-5 pb-16 pt-16 md:px-8 lg:min-h-[720px] lg:grid-cols-[.92fr_1.08fr] lg:pt-6"><Reveal className="relative z-10 max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#c6a06a]/35 bg-white/70 px-3 py-2 text-xs font-bold uppercase tracking-[.12em] text-[#9a6a32]"><Smile size={14} /> Odontologia para toda a família</div><h1 className="text-[3.35rem] font-black leading-[.96] text-[#29353a] sm:text-7xl lg:text-[5.5rem]">Seu sorriso merece <span className="bg-gradient-to-r from-[#c99a55] via-[#a77537] to-[#244e63] bg-clip-text text-transparent">cuidado completo.</span></h1><p className="mt-7 max-w-md text-lg leading-relaxed text-[#5f6664]">Uma equipe de especialistas para acolher cada fase da sua saúde bucal com tecnologia, leveza e atenção.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#localizacao" className="inline-flex items-center gap-2 rounded-full border border-[#9b7947] bg-white px-6 py-4 font-bold text-[#244e63] transition hover:bg-[#fdfbf7]"><MapPin size={19} /> Ver localização</a><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-[#c99a55] to-[#9a6a32] px-6 py-4 font-bold text-white shadow-md shadow-[#9a6a32]/15 transition hover:brightness-105"><MessageCircle size={19} /> Falar no WhatsApp</a></div></Reveal><Reveal delay={0.15} className="relative mt-2 h-[430px] sm:h-[520px] lg:mt-0 lg:h-[650px]"><p className="pointer-events-none absolute inset-x-0 top-[21%] text-center text-4xl font-black leading-none text-[#9a6a32]/[.06] sm:text-5xl lg:text-6xl">CUIDADO<br />INTEGRAL</p><motion.div animate={{ y: [0, -10, 0], rotate: [0, 1, 0] }} transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }} className="absolute inset-0"><Image src="/hero-tooth.png" alt="Dente 3D representando tratamentos odontológicos da LB Odontologia em Niterói" fill priority className="object-contain" sizes="(max-width: 1024px) 100vw, 55vw" /></motion.div></Reveal></div></section>

    <section id="equipe" className="mx-auto max-w-7xl px-5 py-24 md:px-8 lg:py-32"><Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Nossa equipe</p><h2 className="mt-4 text-4xl font-black text-[#29353a] sm:text-5xl">Especialistas para cada sorriso.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-[#5f6664]">Seis profissionais unidos por um atendimento integrado, acolhedor e preciso.</p></Reveal><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{team.map(({ name, specialty, photo }, index) => <Reveal key={name} delay={index * .06} className="overflow-hidden rounded-2xl border border-[#c6a06a]/25 bg-[#fffdf8] shadow-sm"><div className="relative aspect-[3/4] bg-[#e9dec9]"><Image src={photo} alt={`Retrato profissional de ${name}, da equipe LB Odontologia`} fill className="object-contain" sizes="(max-width: 640px) 100vw, 33vw" /><span className="absolute bottom-3 left-3 rounded-full bg-[#fbf9f4]/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#244e63]">Equipe LB</span></div><div className="p-5"><h3 className="font-black text-[#29353a]">{name}</h3><p className="mt-2 text-sm leading-relaxed text-[#5f6664]">{specialty}</p></div></Reveal>)}</div></section>

    <section id="tratamentos" className="bg-[#173a52] py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><Reveal className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#c99a55]">Tratamentos</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Cuidado em todas as fases.</h2></div><p className="border-l-2 border-[#c6a06a] pl-5 text-lg leading-relaxed text-[#dce7e8]">Do primeiro sorriso à reabilitação oral, nossa equipe une especialidades em um plano de cuidado completo.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{treatments.map(([number, title, text, Icon], index) => <Reveal key={title} delay={index * .05} className="relative min-h-[15rem] overflow-hidden rounded-2xl border border-white/15 bg-white/[.06] p-7 transition hover:-translate-y-1 hover:bg-white/[.11]"><div className="flex items-start justify-between"><span className="text-sm font-black tracking-[.16em] text-[#c99a55]">{number}</span><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#c99a55]/15 text-[#c99a55]"><Icon size={21} /></span></div><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-3 leading-relaxed text-[#dce7e8]">{text}</p><div className="absolute bottom-0 left-0 h-1 w-full bg-[#c6a06a]" /></Reveal>)}</div></div></section>

    <section id="procedimentos" className="bg-[#fbf9f4] py-24 lg:py-32">
      <div className="mx-auto max-w-7xl px-5 md:px-8">
        <Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Procedimentos</p><h2 className="mt-4 text-4xl font-black text-[#29353a] sm:text-5xl">Resultados que valorizam você.</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-[#5f6664]">Cada procedimento é conduzido com planejamento, técnica e atenção aos detalhes para preservar a sua identidade.</p></Reveal>
        <div className="mt-12 grid gap-5 lg:grid-cols-2">
          {procedureCases.map((item, index) => <Reveal key={item.image} delay={index * .08} className="overflow-hidden rounded-2xl border border-[#c6a06a]/25 bg-[#fbf8f1] p-3 shadow-lg shadow-[#9a6a32]/10"><Image src={item.image} alt={item.alt} width={1280} height={1184} className="h-auto w-full" sizes="(max-width: 1024px) 100vw, 50vw" /></Reveal>)}
        </div>
        <p className="mt-6 text-sm leading-relaxed text-[#68716f]">Os resultados podem variar de acordo com as características e necessidades de cada pessoa.</p>
      </div>
    </section>

    <section id="depoimentos" className="bg-[#edf3f2] py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Depoimentos</p><h2 className="mt-4 text-4xl font-black text-[#29353a] sm:text-5xl">O que dizem nossos pacientes.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-[#5f6664]">Experiências de quem escolheu a LB Odontologia para cuidar do sorriso.</p></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{testimonials.map((testimonial, index) => <Reveal key={index} delay={index * .08} className="rounded-2xl border border-[#c6a06a]/30 bg-[#fffdf8] p-7 shadow-sm"><div className="flex gap-1 text-[#a77537]" aria-label="5 de 5 estrelas">{Array.from({ length: 5 }, (_, star) => <Star key={star} size={17} fill="currentColor" />)}</div><p className="mt-6 leading-relaxed text-[#5f6664]">“{testimonial.text}”</p><div className="mt-7 border-t border-[#c6a06a]/20 pt-4"><p className="font-black text-[#29353a]">{testimonial.name}</p></div></Reveal>)}</div></div></section>


    <section id="faq" className="bg-[#edf3f2] py-24 lg:py-32">
      <div className="mx-auto grid max-w-7xl gap-12 px-5 md:px-8 lg:grid-cols-[.72fr_1.28fr]">
        <Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Perguntas frequentes</p><h2 className="mt-4 text-4xl font-black text-[#29353a] sm:text-5xl">Tudo começa com uma boa conversa.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-[#5f6664]">Tire as dúvidas iniciais antes da sua avaliação. Para uma orientação personalizada, fale com a nossa equipe.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full border border-[#9b7947] bg-[#fffdf8] px-5 py-3 text-sm font-bold text-[#244e63] transition hover:bg-white"><MessageCircle size={18} /> Tirar uma dúvida</a></Reveal>
        <div className="divide-y divide-[#c6a06a]/25 rounded-2xl border border-[#c6a06a]/30 bg-[#fffdf8] px-6">{faqs.map((faq, index) => { const isOpen = openFaq === index; return <div key={faq.question}><button type="button" className="flex w-full items-center justify-between gap-5 py-6 text-left font-black text-[#29353a]" aria-expanded={isOpen} onClick={() => setOpenFaq(isOpen ? null : index)}>{faq.question}<ChevronDown size={20} className={"shrink-0 text-[#9a5e25] transition-transform " + (isOpen ? "rotate-180" : "")} /></button>{isOpen && <p className="max-w-2xl pb-6 leading-relaxed text-[#5f6664]">{faq.answer}</p>}</div>; })}</div>
      </div>
    </section>

    <section id="localizacao" className="mx-auto grid max-w-7xl gap-10 px-5 py-24 md:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-32"><Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Localização</p><h2 className="mt-4 text-4xl font-black text-[#29353a] sm:text-5xl">Perto de você, em Niterói.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-[#5f6664]">Um espaço preparado para o cuidado odontológico de toda a família.</p><div className="mt-8 space-y-5"><Contact icon={<MapPin />} title="Clínica" text={address} /><Contact icon={<MessageCircle />} title="WhatsApp" text="(21) 99377-0229" /></div><div className="mt-8 flex flex-wrap gap-3"><a href={directions} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-[#9b7947] px-5 py-3 text-sm font-bold text-[#244e63] transition hover:bg-[#fdfbf7]"><Navigation size={18} /> Como chegar</a><a href={googleReviews} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#e8d8b9] px-5 py-3 text-sm font-bold text-[#244e63] transition hover:bg-[#ead39a]"><Star size={17} fill="currentColor" /> Avaliações no Google <ExternalLink size={15} /></a></div></Reveal><Reveal delay={.1} className="relative h-[400px] overflow-hidden rounded-2xl bg-[#dce9ed]"><iframe title="Mapa da clínica odontológica LB Odontologia no Edifício Center Offices, Niterói" className="absolute inset-0 h-[400px] w-full border-0" loading="lazy" src={map} /><div className="pointer-events-none absolute bottom-5 left-5 rounded-xl bg-[#fbf9f4]/95 p-4 shadow-lg"><p className="font-bold text-[#29353a]">Center Offices</p><p className="mt-1 text-sm text-[#5f6664]">Sala 608 · Centro, Niterói</p></div></Reveal></section>
    <footer className="bg-[#173a52] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 sm:flex-row sm:items-center sm:justify-between md:px-8"><div className="flex items-center gap-3"><span className="relative h-10 w-10 overflow-hidden rounded-full bg-[#fbf8f1]"><Image src="/logo-lb.png" alt="Logotipo LB Odontologia" fill className="object-contain p-1" sizes="40px" /></span><div><p className="font-black">LB Odontologia</p><p className="text-sm text-[#dce7e8]">Cuidado especializado</p></div></div><div className="flex flex-wrap items-center gap-4 text-sm"><a href="/politica-de-privacidade" className="font-bold text-[#dce7e8] hover:text-[#c99a55]">Privacidade</a><a href={instagram} target="_blank" rel="noreferrer" className="font-bold text-[#dce7e8] hover:text-[#c99a55]">@lb.odontologia_</a></div></div></footer><a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com a LB Odontologia pelo WhatsApp" className="fixed bottom-5 right-5 z-[60] inline-flex h-14 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[#c99a55] to-[#9a6a32] px-4 text-sm font-bold text-white shadow-xl shadow-[#244e63]/25 transition hover:scale-105 sm:px-5"><MessageCircle size={22} /><span className="hidden sm:inline">WhatsApp</span></a>
  </main>;
}
function Contact({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex items-center gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e8d8b9] text-[#9a6a32]">{icon}</span><div><p className="font-bold text-[#29353a]">{title}</p><p className="mt-0.5 text-sm text-[#5f6664]">{text}</p></div></div>; }

